name: "Publish Site to Azure"
on: 
  push: 
    branches: 
      - main

jobs: 
  build-publish: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      # Load cache
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      # Install dependencies
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 6.0.2
          run_install: |
            - args: [--frozen-lockfile]
      # Build
      - run: pnpm build
      # Upload
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with: 
          container_name: $web
          extra_args: "--destination-path potential-adventure/"
          connection_string: ${{ secrets.AZURE_CONNECTION_STRING }}
          source_dir: public
          sync: true
